spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: mscloud-config-dev
    datasource:
    url: jdbc:mysql://localhost:3306/dev             # 数据库名称
     
server:
    port: 9001
       

---
spring:
    profiles: test
    application:
        name: mscloud-config-test
    datasource:
    url: jdbc:mysql://localhost:3306/test             # 数据库名称
 
server:
    port: 9002        
    